version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:80"
    env_file:
      - .env
    environment:
      - ENV=development
    restart: unless-stopped
    # volumes:  # Elimina o comenta esta línea para evitar sobrescribir el build
    #   - .:/app
